import type { Metadata } from "next";
import localFont from "next/font/local";
import { Locale, i18n } from '../../../../i18n.config'
import "./globals.css";
import Header from "./component/header/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale : any)  => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params 
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale }
}>) {
  return (
    <html data-theme={process.env.APP_THEME}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header/>
        {children}
      </body>
    </html>
  );
} 
